# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- task: DownloadSecureFile@1
  displayName: SecFile
  inputs:
    secureFile: '.env.development.local'

- script: echo "$(SecFile.secureFilePath)"